// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication2;

namespace WebApplication2.Migrations
{
    [DbContext(typeof(ResourcesContext))]
    [Migration("20181115234742_AddAllModels")]
    partial class AddAllModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:btree_gin", "'btree_gin', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:btree_gist", "'btree_gist', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:citext", "'citext', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:cube", "'cube', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:dblink", "'dblink', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:dict_int", "'dict_int', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:dict_xsyn", "'dict_xsyn', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:earthdistance", "'earthdistance', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:fuzzystrmatch", "'fuzzystrmatch', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:hstore", "'hstore', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:intarray", "'intarray', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:ltree", "'ltree', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:pg_stat_statements", "'pg_stat_statements', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:pg_trgm", "'pg_trgm', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:pgcrypto", "'pgcrypto', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:pgrowlocks", "'pgrowlocks', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:pgstattuple", "'pgstattuple', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:plv8", "'plv8', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:tablefunc", "'tablefunc', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:unaccent", "'unaccent', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", "'uuid-ossp', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:xml2", "'xml2', '', ''")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WebApplication2.Domain.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<int>("Role");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
